### ISSUE TITLE
Clicking on CombinedCell label will not refresh the view

### ISSUE THREAD

**Issue by Kharg** [mozkomor05/espocrm-email-preview-extension#11]
Clicking on the CombinedCell label in the list view will not refresh the view but will generate an error.

![image](https://github.com/mozkomor05/espocrm-email-preview-extension/assets/32223252/a952e5bf-b502-4623-9fee-736845c55af4)

**Comment by digitalextremist** [comment]
@Kharg have you fixed this in your fork?

**Comment by Kharg** [comment]
> @Kharg have you fixed this in your fork?

No.

**Comment by mozkomor05** [comment]
Thanks for reporting, I'll have a look at it.

**Comment by mozkomor05** [comment]
@Kharg  Can you still reproduce the issue?

**Comment by Kharg** [comment]
I will build from the latest commit and let you know as soon as possible.

**Comment by mozkomor05** [comment]
Thank you. Here's the built extension. I can not reproduce the issue with Espo 7.5.1.
[EmailCombinedView-v0.0.7.zip](https://github.com/mozkomor05/espocrm-email-preview-extension/files/11787334/EmailCombinedView-v0.0.7.zip)

**Comment by Kharg** [comment]
Let's say that it fixes the issue but it brings a new issue. clicking on the label will leave the current record in "loading" mode until you switch records or refresh the page

![image](https://github.com/mozkomor05/espocrm-email-preview-extension/assets/32223252/224e4e6a-18b9-40b5-9617-6cd8177a9940)

**Comment by mozkomor05** [comment]
What version of Espo do you use? Can you please describe the steps to reproduce the bug?

**Comment by Kharg** [comment]
@mozkomor05 Hi,
Espo 7.5.2
Video with bug reproduction
https://www.awesomescreenshot.com/video/18464015?key=6eef73b1ce5772057034615af84c90ff

**Comment by mozkomor05** [comment]
Thank you very much.

Fixed by https://github.com/mozkomor05/espocrm-email-preview-extension/commit/ab0bd0c9161ecc56e1dd032244e79db20ec029de

**Comment by Kharg** [comment]
Thanks, are you gonna compile a new version soon? :)

**Comment by mozkomor05** [comment]
@Kharg Released :+1:
