### ISSUE TITLE
Design problems

### ISSUE THREAD

**Issue by ChrisSka** [mozkomor05/espocrm-email-preview-extension#13]
Hello,
have slight design problems with the current version.
When I scroll down in a long email, yes the inbox floats down with it.
If I scroll up again, the inbox stays above the search field.
This doesn't always happen, but it does happen from time to time.

![Screenshot 2023-07-17 11 13 30](https://github.com/mozkomor05/espocrm-email-preview-extension/assets/68166740/b020fb1f-3377-4e81-a690-79b292d64ec3)

**Comment by mozkomor05** [comment]
I am not able to consistently reproduce, however, it happens to me from time to time as well. I can confirm that the issue persists with Espo v8.0+.

**Comment by mozkomor05** [comment]
Found the bug. It happens after switching between list and combined mode.
