### ISSUE TITLE
Espo v8 Compatibility

### ISSUE THREAD

**Issue by o-data** [mozkomor05/espocrm-email-preview-extension#15]
EspoCRM: v8
CombineEmail: v0.1.0

Recently upgrade to Espo v8 and it seem it no longer compatibile. Whether if I'm using default view or Combined View.

Uninstall/Disable the extension make email work again.

**Comment by Kharg** [comment]
Hi @mozkomor05 I think that at this point you could just remove the extender and limit the compatibility of the extension to Espo 7.5+ to make it works.

**Comment by mozkomor05** [comment]
@Kharg @o-data Sorry, I didn't have much time to fix the bug. I managed to make an extender for Espo v8.0+. but it doesn't affect this extension in the end, because it doesn't use the extender at all :D The fix is much easier and you can expect a release today.

**Comment by Kharg** [comment]
> @mozkomor05 thanks Moz!
> 
> 
> 
> When I install this version, v0.1.0 didn't get overwrite with 0.1.1, both version is installed instead. Was this intentional or bug or something else?
> 
> 
> 
> Anyway I just uninstall v0.1.0. Maybe because it was disable it didn't get overwrite/update?

Is version 0.1.0 uninstalled? If so installing a new version will not "overwrite" it because it's not installed.

**Comment by mozkomor05** [comment]
Yep. There are both uninstalled and installed extensions in the list. If you want to remove them completely, you have to click on the little arrow and choose "Remove".
