### ISSUE TITLE
[Feature Request] Support "Print" email option

### ISSUE THREAD

**Issue by o-data** [mozkomor05/espocrm-email-preview-extension#19]
I would like to be able to print email directly from the preview ... option.

Here is the menu normally, the option "Print" (As of version EspoCRM 8.x? Feature) will allow user to print a neat/plain looking email.

![](https://github.com/mozkomor05/espocrm-email-preview-extension/assets/67723461/e23f7f56-0b50-42c9-bc27-a6d25a9e2f14)

Current the extension only have these option.

![](https://github.com/mozkomor05/espocrm-email-preview-extension/assets/67723461/85cc143d-1840-41d9-8ead-8bd195bf9651)

**Comment by Kharg** [comment]
I think I will release an update and fix all the issues.

**Comment by Kharg** [comment]
@o-data 

https://github.com/Kharg/espocrm-email-preview-extension/releases/tag/0.1.2

**Comment by o-data** [comment]
Fixed by Kharg fork
