### ISSUE TITLE
Removing record switches folder if not in inbox

### ISSUE THREAD

**Issue by Kharg** [mozkomor05/espocrm-email-preview-extension#5]
Removing a record while on a different folder than inbox switches folder and reselect the first record from the inbox folder.

**Comment by mozkomor05** [comment]
Cannot reproduce. I tried removing emails in `All` and `Sent` folders and, for me, it alwyas reselects the next record in list.

**Comment by Kharg** [comment]
I don't know why but that happens to me, I will try to test it with different instances.
