### ISSUE TITLE
[Minor] ['Typo] Combined (combine) on mouse hover

### ISSUE THREAD

**Issue by o-data** [mozkomor05/espocrm-email-preview-extension#6]
v.0.0.3

A very small 'bug' that is so minor I thought I could try to do a Pull Request for but I can't find where the code is :(

Anyway on popup, the original view "List" is uppercase, so icon popup for "combine" should be Title Case and written as "Combined" too. Here is a screenshot for reference:

![image](https://user-images.githubusercontent.com/67723461/205567536-b95b2926-3ce1-4dca-80f7-42c9728cd72f.png)

PS: Love the style, it make reading email on wide-screen desktop easier.

**Comment by mozkomor05** [comment]
Thanks
