### ISSUE TITLE
First column wider?

### ISSUE THREAD

**Issue by ChrisSka** [mozkomor05/espocrm-email-preview-extension#7]
Hello, the extension is already practical.
But could you somehow make the layout different?
At the moment you see the folders on the left and they are already somewhat narrowed.
Maybe the first column a little wider and the preview narrower?
![Screenshot 2023-04-24 23 50 17](https://user-images.githubusercontent.com/68166740/234124742-32be400f-ef3b-45ad-aa57-02f6fe3d84f5.png)

**Comment by mozkomor05** [comment]
I've made some changes since I last uploaded the extension to GitHub. I'll publish them when I get home (in ~3 days) as soon as possible.

**Comment by ChrisSka** [comment]
That sounds good. I think I can wait that long.

**Comment by mozkomor05** [comment]
https://github.com/mozkomor05/espocrm-email-preview-extension/releases/tag/v0.0.5
