### ISSUE TITLE
Buttons overflow

### ISSUE THREAD

**Issue by Kharg** [mozkomor05/espocrm-email-preview-extension#8]
Hi,
Nice update!

I think that the  create task button should instead be a dropdown action, as it may make the design overflow if there are too many buttons with long names. same for the delete button
![image](https://user-images.githubusercontent.com/32223252/235335932-fd001678-b1aa-422e-98ba-98bb188f5089.png)

**Comment by mozkomor05** [comment]
"Reply to All" is redundant, as behaviour of "Reply" can be set in preferences. I'll move it into the dropdown, that shoudl create some spare space.
